templates:
  infinite-loop: "bash -c 'while sleep {{ .sleep }}; do {{ .cmd }}; done'"

processes:
  clock:
    template: "infinite-loop"
    vars:
      sleep: 1
      cmd: "date +\"%T\""
    tags: ["demo"]

  ping-error:
    template: "ping foo"
    tags: ["demo", "ping"]

  ping-ok:
    template: "ping localhost"
    tags: ["demo", "ping"]

  ignore-signals: "go run examples/ignore-signals.go"

  inline: "ping localhost"
