name: Examples

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

env:
  GO_DAEMON_CACHE_BUILD: true

jobs:

  examples:
    name: Examples
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: gofmt
        run: make format-ci

      - name: Build
        run: make build

      - name: Clock
        run: make clock

      - name: Ignore signals
        run: make ignore-signals

      - name: Ping
        run: make ping-ok

      - name: Errors
        run: make ping-error

      - name: Two daemons
        run: make ping

      - name: Inline
        run: make inline

      - name: Help
        run: make help
