name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

env:
  GO_DAEMON_CACHE_BUILD=1

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make tests-unit

#      - name: Test coverage
#        run: make code-coverage
#
#      - name: Send coverage
#        uses: shogo82148/actions-goveralls@v1
#        with:
#          path-to-profile: coverage.out
#          flag-name: Go-${{ matrix.go }}

      - name: Ignore signals
        run: make ignore-signals

      - name: Ping
        run: make ping-ok

      - name: Ping error
        run: make ping-error

      - name: Help
        run: make help
